# Generated by Django 3.2.9 on 2022-03-25 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Район + период')),
                ('time', models.DateTimeField(max_length=500, verbose_name='Время')),
            ],
        ),
        migrations.CreateModel(
            name='Articles_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anons', models.CharField(max_length=500, verbose_name='Имя расходов')),
                ('numb', models.IntegerField(verbose_name='Цифра расходов')),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.articles')),
            ],
        ),
    ]
